# Database configuration
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=root
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:mysql://localhost:3306/sales_management

# Hibernate ORM configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.sql-load-script=import.sql

# JSON Configuration
quarkus.jackson.fail-on-empty-beans=false
# C?u hình b?o m?t s? d?ng JPA (Database)
quarkus.security.users.embedded.enabled=false
quarkus.http.auth.basic=true
# 1. M? c?a công khai cho các API liên quan ??n Auth (??ng ký/??ng nh?p)
quarkus.http.auth.permission.public.paths=/api/auth/*
quarkus.http.auth.permission.public.policy=permit

# 2. Khóa t?t c? các API nghi?p v?, yêu c?u ph?i ??ng nh?p m?i ???c vào
quarkus.http.auth.permission.authenticated.paths=/api/products/*,/api/orders/*,/api/customers/*,/api/statistics/*
quarkus.http.auth.permission.authenticated.policy=authenticated